name: Daily Perform Cleanup Development

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CRON_SECRET_PASS_DEV: ${{ secrets.CRON_SECRET_PASS_DEV }}
      API_ENDPOINT_DEV: ${{ secrets.API_ENDPOINT_DEV }}
      API_LANGUAGE: ${{ secrets.API_LANGUAGE }}
      API_VERSION: ${{ secrets.API_VERSION }}

    steps:
      - name: Daily Perform Cleanup
        run: |
          curl -H "Authorization: $CRON_SECRET_PASS_DEV" \
               -H "Api-Language: $API_LANGUAGE" \
               -H "Api-Version: $API_VERSION" \
               -X GET "$API_ENDPOINT_DEV/crons/perform-cleanup"